import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "ParityScope's terms of service governing use of our AI fairness platform, SDK, and website.",
};

export default function TermsPage() {
  return (
    <section className="px-4 py-section sm:px-6 lg:px-8">
      <div className="mx-auto max-w-4xl">
        <h1 className="text-h1 font-bold text-navy">Terms of Service</h1>
        <p className="mt-4 text-body-lg text-medium-gray">
          Last updated: March 2026
        </p>

        <div className="mt-12 space-y-10 text-medium-gray leading-relaxed">
          <div>
            <h2 className="text-h3 font-semibold text-navy">
              1. Acceptance of Terms
            </h2>
            <p className="mt-3">
              These Terms of Service (&quot;Terms&quot;) govern your access to
              and use of the ParityScope website (parityscope.com), SDK,
              API, and related services (collectively, the
              &quot;Services&quot;) provided by ParityScope (&quot;we,&quot;
              &quot;our,&quot; or &quot;us&quot;). By accessing or using our
              Services, you agree to be bound by these Terms. If you are using
              our Services on behalf of an organization, you represent that you
              have the authority to bind that organization to these Terms.
            </p>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              2. Description of Services
            </h2>
            <p className="mt-3">
              ParityScope provides AI fairness auditing, monitoring, and
              mitigation tools for healthcare organizations. Our Services
              include:
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>Python SDK for on-premise fairness analysis</li>
              <li>REST API for programmatic access</li>
              <li>Cloud monitoring dashboard and alerting</li>
              <li>Compliance report generation</li>
              <li>Professional assessment services</li>
            </ul>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              3. Account Registration
            </h2>
            <p className="mt-3">
              To access certain features of our Services, you must create an
              account. You agree to provide accurate, current, and complete
              information, maintain the security of your credentials, and
              promptly notify us of any unauthorized access. You are responsible
              for all activity under your account.
            </p>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              4. License and Usage Rights
            </h2>
            <h3 className="mt-4 font-semibold text-dark-gray">4.1 SDK License</h3>
            <p className="mt-2">
              Subject to these Terms and your subscription agreement, we grant
              you a non-exclusive, non-transferable, revocable license to
              install and use the ParityScope SDK within your organization for
              the purpose of fairness analysis of your AI models. You may not
              sublicense, redistribute, or reverse-engineer the SDK.
            </p>
            <h3 className="mt-4 font-semibold text-dark-gray">4.2 API Access</h3>
            <p className="mt-2">
              API access is subject to rate limits and usage quotas defined in
              your subscription plan. API keys are confidential and must not be
              shared or exposed in client-side code. We reserve the right to
              throttle or suspend API access for abuse or excessive usage.
            </p>
            <h3 className="mt-4 font-semibold text-dark-gray">4.3 Reports</h3>
            <p className="mt-2">
              You may use compliance reports generated by ParityScope for
              internal purposes, regulatory submissions, and stakeholder
              communications. Reports may not be resold or used to provide
              competing services.
            </p>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              5. Data and Privacy
            </h2>
            <p className="mt-3">
              Our SDK is designed to process data locally within your
              infrastructure. We do not access, store, or process patient data
              or protected health information (PHI). For data we do collect (as
              described in our Privacy Policy), we maintain appropriate security
              measures. Our data practices are detailed in our{" "}
              <a href="/privacy" className="text-teal underline">
                Privacy Policy
              </a>
              .
            </p>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              6. Prohibited Uses
            </h2>
            <p className="mt-3">You may not:</p>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>
                Use our Services to circumvent or evade fairness regulations or
                compliance obligations
              </li>
              <li>
                Misrepresent audit results or generate fraudulent compliance
                documentation
              </li>
              <li>
                Reverse-engineer, decompile, or disassemble the SDK or platform
              </li>
              <li>
                Use automated means to scrape, crawl, or harvest data from our
                website or API beyond authorized usage
              </li>
              <li>
                Sublicense, resell, or redistribute our Services without written
                authorization
              </li>
              <li>
                Use our Services in any manner that violates applicable law or
                regulation
              </li>
            </ul>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              7. Fees and Payment
            </h2>
            <p className="mt-3">
              Subscription fees are specified in your order form or subscription
              agreement. Fees are non-refundable except as required by law.
              We reserve the right to change pricing with 30 days&apos; notice.
              Late payments may result in service suspension after 15 days&apos;
              written notice.
            </p>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              8. Intellectual Property
            </h2>
            <p className="mt-3">
              ParityScope retains all rights, title, and interest in the
              Services, including all intellectual property rights. Your data
              remains your property. Aggregated, anonymized usage data may be
              used by ParityScope to improve our Services and for research
              purposes.
            </p>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              9. Disclaimers
            </h2>
            <p className="mt-3">
              ParityScope provides fairness analysis tools to support your
              compliance efforts, but we do not guarantee regulatory compliance.
              Our Services are provided &quot;as is&quot; and &quot;as
              available.&quot; We do not warrant that the Services will be
              uninterrupted, error-free, or that any specific fairness outcome
              will be achieved. You are responsible for your own compliance
              decisions.
            </p>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              10. Limitation of Liability
            </h2>
            <p className="mt-3">
              To the maximum extent permitted by law, ParityScope&apos;s total
              liability arising from these Terms or the use of our Services
              shall not exceed the fees paid by you in the 12 months preceding
              the claim. We are not liable for indirect, incidental, special,
              consequential, or punitive damages.
            </p>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              11. Indemnification
            </h2>
            <p className="mt-3">
              You agree to indemnify and hold harmless ParityScope from claims,
              damages, and expenses arising from your use of the Services,
              violation of these Terms, or infringement of third-party rights.
            </p>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              12. Termination
            </h2>
            <p className="mt-3">
              Either party may terminate the subscription with 30 days&apos;
              written notice. We may suspend or terminate access immediately
              for material breach, including prohibited uses. Upon termination,
              your license to use the SDK and API ceases. You may export your
              data for 30 days following termination.
            </p>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              13. Governing Law
            </h2>
            <p className="mt-3">
              These Terms are governed by the laws of the State of Delaware,
              United States, without regard to conflict of law principles. Any
              disputes arising from these Terms shall be resolved through
              binding arbitration in accordance with the rules of the American
              Arbitration Association.
            </p>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              14. Changes to These Terms
            </h2>
            <p className="mt-3">
              We may update these Terms from time to time. We will provide
              notice of material changes via email or a prominent notice on our
              website. Continued use of our Services after changes take effect
              constitutes acceptance of the updated Terms.
            </p>
          </div>

          <div>
            <h2 className="text-h3 font-semibold text-navy">
              15. Contact
            </h2>
            <p className="mt-3">
              For questions about these Terms, please contact us at:
            </p>
            <div className="mt-3">
              <p>ParityScope</p>
              <p>Email: legal@parityscope.com</p>
              <p>General: hello@parityscope.com</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
