"""Report generation — structured audit reports for regulatory documentation.

Generates JSON reports and human-readable summaries from audit results.
Designed to satisfy documentation requirements across jurisdictions.
"""

from __future__ import annotations

import json

from parityscope.audit.result import AuditResult, FairnessLevel
from parityscope.regulations.mapping import get_compliance_requirements


def generate_json_report(result: AuditResult, indent: int = 2) -> str:
    """Generate a full JSON audit report.

    The JSON report contains all audit metadata, metric results, and
    compliance information needed for regulatory documentation.
    """
    report = result.to_dict()

    # Add compliance mapping if jurisdiction is specified
    if result.jurisdiction:
        requirements = get_compliance_requirements(result.jurisdiction)
        report["compliance"] = {
            "jurisdiction": result.jurisdiction,
            "requirements": [
                {
                    "regulation": r.regulation,
                    "article": r.article,
                    "requirement": r.requirement,
                    "description": r.description,
                    "evidence_needed": r.evidence_needed,
                    "status": _assess_requirement_status(result, r.article),
                }
                for r in requirements
            ],
        }

    return json.dumps(report, indent=indent, default=str)


def generate_summary(result: AuditResult) -> str:
    """Generate a human-readable text summary of the audit.

    Suitable for executive reporting and quick review.
    """
    lines = []
    lines.append("=" * 70)
    lines.append(f"PARITYSCOPE FAIRNESS AUDIT REPORT")
    lines.append("=" * 70)
    lines.append(f"Model:           {result.model_name}")
    lines.append(f"Audit ID:        {result.audit_id}")
    lines.append(f"Timestamp:       {result.timestamp}")
    lines.append(f"Total samples:   {result.total_samples:,}")
    lines.append(f"Jurisdiction:    {result.jurisdiction or 'Not specified'}")
    lines.append(f"Clinical domain: {result.clinical_domain or 'Not specified'}")
    lines.append(f"Attributes:      {', '.join(result.protected_attributes)}")
    lines.append("")

    # Overall assessment
    level_display = {
        FairnessLevel.FAIR: "FAIR",
        FairnessLevel.MARGINAL: "MARGINAL - Review Recommended",
        FairnessLevel.UNFAIR: "UNFAIR - Action Required",
    }
    lines.append(f"OVERALL ASSESSMENT: {level_display[result.overall_fairness]}")
    lines.append("-" * 70)
    lines.append(
        f"  Fair: {len(result.fair_metrics)}  |  "
        f"Marginal: {len(result.marginal_metrics)}  |  "
        f"Unfair: {len(result.unfair_metrics)}"
    )
    lines.append("")

    # Group demographics
    lines.append("GROUP DEMOGRAPHICS:")
    lines.append("-" * 70)
    for group_key, count in sorted(result.group_counts.items()):
        pct = count / result.total_samples * 100
        lines.append(f"  {group_key}: {count:,} ({pct:.1f}%)")
    lines.append("")

    # Metric results — unfair first, then marginal, then fair
    for section_name, metrics in [
        ("UNFAIR METRICS (Action Required)", result.unfair_metrics),
        ("MARGINAL METRICS (Review Recommended)", result.marginal_metrics),
        ("FAIR METRICS", result.fair_metrics),
    ]:
        if metrics:
            lines.append(f"{section_name}:")
            lines.append("-" * 70)
            for m in metrics:
                lines.append(f"  {m.display_name}")
                lines.append(f"    Disparity: {m.disparity:.4f} (threshold: {m.threshold:.4f})")
                if m.group_results:
                    for g in m.group_results:
                        lines.append(f"    {g.group_label}: {g.rate:.4f} (n={g.sample_size:,})")
            lines.append("")

    lines.append("=" * 70)
    lines.append("Report generated by ParityScope v0.1.0")
    lines.append("https://parityscope.com")
    lines.append("=" * 70)

    return "\n".join(lines)


def _assess_requirement_status(result: AuditResult, article: str) -> str:
    """Assess whether a compliance requirement is addressed by the audit."""
    # Simplified mapping — a real implementation would have more nuanced logic
    if "monitoring" in article.lower() or "post-market" in article.lower():
        return "requires_continuous_monitoring"
    if result.overall_fairness == FairnessLevel.FAIR:
        return "addressed"
    if result.overall_fairness == FairnessLevel.MARGINAL:
        return "partially_addressed"
    return "action_required"
