"""Shared PDF infrastructure for all report generators.

Provides consistent colors, styles, table helpers, and page templates
used across all ParityScope PDF reports.
"""

from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from parityscope.audit.result import AuditResult, FairnessLevel

# Colour palette
DARK = colors.HexColor("#1a1a2e")
PRIMARY = colors.HexColor("#16213e")
ACCENT = colors.HexColor("#0f3460")
GREEN = colors.HexColor("#2d6a4f")
YELLOW = colors.HexColor("#e9c46a")
RED = colors.HexColor("#e63946")
LIGHT_GREEN = colors.HexColor("#d8f3dc")
LIGHT_YELLOW = colors.HexColor("#fff3cd")
LIGHT_RED = colors.HexColor("#f8d7da")
GREY_BG = colors.HexColor("#f8f9fa")
GREY_BORDER = colors.HexColor("#dee2e6")
WHITE = colors.white


def level_color(level: FairnessLevel) -> colors.Color:
    return {FairnessLevel.FAIR: GREEN, FairnessLevel.MARGINAL: YELLOW, FairnessLevel.UNFAIR: RED}[level]


def level_bg(level: FairnessLevel) -> colors.Color:
    return {FairnessLevel.FAIR: LIGHT_GREEN, FairnessLevel.MARGINAL: LIGHT_YELLOW, FairnessLevel.UNFAIR: LIGHT_RED}[level]


def level_label(level: FairnessLevel) -> str:
    return {FairnessLevel.FAIR: "FAIR", FairnessLevel.MARGINAL: "MARGINAL", FairnessLevel.UNFAIR: "UNFAIR"}[level]


def build_styles() -> dict[str, ParagraphStyle]:
    """Build the standard ParityScope paragraph styles."""
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("ReportTitle", parent=base["Title"], fontSize=28, leading=34, textColor=DARK, spaceAfter=6),
        "subtitle": ParagraphStyle("ReportSubtitle", parent=base["Normal"], fontSize=12, leading=16, textColor=colors.HexColor("#6c757d"), spaceAfter=20),
        "h1": ParagraphStyle("H1", parent=base["Heading1"], fontSize=18, leading=22, textColor=PRIMARY, spaceBefore=20, spaceAfter=10),
        "h2": ParagraphStyle("H2", parent=base["Heading2"], fontSize=14, leading=18, textColor=ACCENT, spaceBefore=14, spaceAfter=8),
        "h3": ParagraphStyle("H3", parent=base["Heading3"], fontSize=12, leading=16, textColor=ACCENT, spaceBefore=10, spaceAfter=6),
        "body": ParagraphStyle("Body", parent=base["Normal"], fontSize=10, leading=14, textColor=DARK),
        "small": ParagraphStyle("Small", parent=base["Normal"], fontSize=8, leading=10, textColor=colors.HexColor("#6c757d")),
        "verdict_fair": ParagraphStyle("VerdictFair", parent=base["Normal"], fontSize=22, leading=28, textColor=GREEN, alignment=1),
        "verdict_unfair": ParagraphStyle("VerdictUnfair", parent=base["Normal"], fontSize=22, leading=28, textColor=RED, alignment=1),
        "cell": ParagraphStyle("Cell", parent=base["Normal"], fontSize=9, leading=12, textColor=DARK),
        "cell_bold": ParagraphStyle("CellBold", parent=base["Normal"], fontSize=9, leading=12, textColor=DARK, fontName="Helvetica-Bold"),
        "cell_header": ParagraphStyle("CellHeader", parent=base["Normal"], fontSize=9, leading=12, textColor=WHITE, fontName="Helvetica-Bold"),
    }


def styled_table(data: list[list], col_widths: list[float] | None = None, header_bg: colors.Color = PRIMARY) -> Table:
    """Create a consistently styled table with header row."""
    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), header_bg),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, GREY_BORDER),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, GREY_BG]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return table


def header_footer(canvas, doc):
    """Draw page header line and footer with page number."""
    canvas.saveState()
    canvas.setStrokeColor(PRIMARY)
    canvas.setLineWidth(1.5)
    canvas.line(doc.leftMargin, letter[1] - 40, letter[0] - doc.rightMargin, letter[1] - 40)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#6c757d"))
    canvas.drawString(doc.leftMargin, letter[1] - 35, "ParityScope Fairness Audit Report")
    canvas.setFont("Helvetica", 8)
    canvas.drawCentredString(letter[0] / 2, 30, f"Page {doc.page}")
    canvas.drawRightString(letter[0] - doc.rightMargin, 30, "Generated by ParityScope v0.2.0 — parityscope.com")
    canvas.restoreState()


def create_document(buf: BytesIO) -> BaseDocTemplate:
    """Create a standard ParityScope document."""
    doc = BaseDocTemplate(buf, pagesize=letter, leftMargin=0.75 * inch, rightMargin=0.75 * inch, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height - 20, id="main")
    doc.addPageTemplates([PageTemplate(id="all", frames=frame, onPage=header_footer)])
    return doc


def verdict_box(result: AuditResult, doc, styles: dict) -> list:
    """Build the overall verdict/assessment box. Returns story elements."""
    verdict_style = styles["verdict_fair"] if result.overall_fairness == FairnessLevel.FAIR else styles["verdict_unfair"]
    bg = level_bg(result.overall_fairness)
    clr = level_color(result.overall_fairness)

    data = [[Paragraph(f"Overall Assessment: <b>{level_label(result.overall_fairness)}</b>", verdict_style)]]
    table = Table(data, colWidths=[doc.width])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), bg),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 16),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 16),
        ("BOX", (0, 0), (-1, -1), 1, clr),
    ]))
    return [table, Spacer(1, 16)]


def metadata_table(result: AuditResult, doc, styles: dict) -> Table:
    """Build standard audit metadata table."""
    pairs = [
        ("Audit ID", result.audit_id),
        ("Timestamp", str(result.timestamp)),
        ("Total Samples", f"{result.total_samples:,}"),
        ("Protected Attributes", ", ".join(result.protected_attributes)),
        ("Jurisdiction", result.jurisdiction or "Not specified"),
        ("Clinical Domain", result.clinical_domain or "Not specified"),
    ]
    data = [[Paragraph(f"<b>{k}</b>", styles["cell"]), Paragraph(str(v), styles["cell"])] for k, v in pairs]
    t = Table(data, colWidths=[2 * inch, doc.width - 2 * inch])
    t.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, GREY_BORDER),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [GREY_BG, WHITE]),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return t
